import type { AbilityId } from './types.js';

export interface NewAbilityDef {
  id: AbilityId;
  name: string;
  description: string;
  devDescription?: string;
}

export const NEW_ABILITIES: Record<string, NewAbilityDef> = {
  'flame-emperor': {
    id: 'flame-emperor' as AbilityId,
    name: 'Flame Emperor',
    description: 'Commands the team\u2019s Fire-types, strengthening every Fire ally.',
    devDescription: 'Every Fire-type teammate fights at 1.1\u00d7 its stats.',
  },
  'tide-matriarch': {
    id: 'tide-matriarch' as AbilityId,
    name: 'Tide Matriarch',
    description: 'Nurtures the team\u2019s Water-types, bolstering them and gently healing each turn.',
    devDescription:
      'Every Water-type teammate fights at 1.08\u00d7 its stats and recovers a sliver of HP each turn.',
  },
  'iron-marshal': {
    id: 'iron-marshal' as AbilityId,
    name: 'Iron Marshal',
    description: 'Steel-type allies take less damage from every hit.',
    devDescription: 'Steel-type teammates take only 0.92\u00d7 damage.',
  },
  'fairy-court': {
    id: 'fairy-court' as AbilityId,
    name: 'Fairy Court',
    description: 'Fairy-type allies hit harder and their stats can never be lowered.',
    devDescription: 'Fairy-type teammates deal 1.08\u00d7 damage and ignore stat drops.',
  },
  'shadow-cabinet': {
    id: 'shadow-cabinet' as AbilityId,
    name: 'Shadow Cabinet',
    description: 'Dark-type allies strike harder against foes afflicted by status.',
    devDescription: 'Dark-type teammates deal 1.12\u00d7 damage to statused foes.',
  },
  'hive-queen': {
    id: 'hive-queen' as AbilityId,
    name: 'Hive Queen',
    description: 'With two or more Bug-types on the team, everyone moves a little faster.',
    devDescription: 'When the team has 2+ Bug-types, all teammates gain 1.06\u00d7 Speed.',
  },
  'sky-lord': {
    id: 'sky-lord' as AbilityId,
    name: 'Sky Lord',
    description: 'Flying-type allies enter battle with a burst of Speed.',
    devDescription: 'Flying-type teammates enter with +1 Speed.',
  },
  'grass-warden': {
    id: 'grass-warden' as AbilityId,
    name: 'Grass Warden',
    description: 'Grass-type allies recover a little HP at the end of every turn.',
  },
  'volt-squad': {
    id: 'volt-squad' as AbilityId,
    name: 'Volt Squad',
    description: 'Electric-type allies\u2019 Electric moves hit harder.',
    devDescription: 'Electric-type teammates\u2019 Electric moves deal 1.1\u00d7 damage.',
  },
  'pack-alpha': {
    id: 'pack-alpha' as AbilityId,
    name: 'Pack Alpha',
    description: 'Fighting-type allies hit harder and ignore Intimidate.',
    devDescription: 'Fighting-type teammates deal 1.1\u00d7 Attack damage and ignore Intimidate.',
  },
  diviner: {
    id: 'diviner' as AbilityId,
    name: 'Diviner',
    description: 'While it\u2019s on the team, celestial signs are easier to roll.',
  },
  fortune: {
    id: 'fortune' as AbilityId,
    name: 'Fortune',
    description: 'While it\u2019s on the team, shiny Pokémon are more likely to appear.',
  },
  'treasure-hound': {
    id: 'treasure-hound' as AbilityId,
    name: 'Treasure Hound',
    description: 'While it\u2019s on the team, item events appear more often.',
    devDescription: 'While it\u2019s on the team, the run gains +1 item event.',
  },
  curator: {
    id: 'curator' as AbilityId,
    name: 'Curator',
    description: 'While it\u2019s on the team, relic choices offer an extra option.',
    devDescription: 'While it\u2019s on the team, relic choices offer 4 options instead of 3.',
  },
  scout: {
    id: 'scout' as AbilityId,
    name: 'Scout',
    description: 'While it\u2019s on the team, you can see foe types on the master map.',
  },
  veteran: {
    id: 'veteran' as AbilityId,
    name: 'Veteran',
    description: 'Hits harder against gym leaders and tougher trainers.',
    devDescription: 'Deals 1.05\u00d7 damage against gym leaders and higher-tier foes.',
  },
  bargain: {
    id: 'bargain' as AbilityId,
    name: 'Bargain',
    description: 'While it\u2019s on the team, type-booster relics show up more often.',
    devDescription: 'While it\u2019s on the team, type-booster relic weight is doubled in item events.',
  },
  'thorn-wreath': {
    id: 'thorn-wreath' as AbilityId,
    name: 'Thorn Wreath',
    description: 'When it faints, the attacker is badly poisoned.',
  },
  'parting-gift': {
    id: 'parting-gift' as AbilityId,
    name: 'Parting Gift',
    description: 'When it faints, the next ally enters free of status.',
  },
  'soul-battery': {
    id: 'soul-battery' as AbilityId,
    name: 'Soul Battery',
    description: 'When it faints, the next ally enters with restored health.',
    devDescription: 'When it faints, the next ally enters healed for 20% of its max HP.',
  },
  grudge: {
    id: 'grudge' as AbilityId,
    name: 'Grudge',
    description: 'When a direct hit knocks it out, the finishing move loses PP.',
    devDescription: 'When a direct hit knocks it out, the finishing move loses 2 PP.',
  },
  'revenge-cry': {
    id: 'revenge-cry' as AbilityId,
    name: 'Revenge Cry',
    description: 'When it faints, the next ally enters with raised Defense.',
    devDescription: 'When it faints, the next ally enters with +2 Defense.',
  },
  'torch-pass': {
    id: 'torch-pass' as AbilityId,
    name: 'Torch Pass',
    description: 'When it faints, the next ally\u2019s Fire moves burn hotter for a few turns.',
    devDescription: 'When it faints, the next ally\u2019s Fire moves deal 1.25\u00d7 for 3 turns.',
  },
  'burden-bearer': {
    id: 'burden-bearer' as AbilityId,
    name: 'Burden Bearer',
    description: 'When a direct hit knocks it out, the attacker loses a chunk of HP.',
    devDescription: 'When a direct hit knocks it out, the attacker loses 15% of its max HP.',
  },
  daunt: {
    id: 'daunt' as AbilityId,
    name: 'Daunt',
    description: 'On entry, it lowers the foe\u2019s Speed a stage.',
  },
  screech: {
    id: 'screech' as AbilityId,
    name: 'Screech',
    description: 'On entry, it lowers the foe\u2019s Defense a stage.',
  },
  'eerie-aura': {
    id: 'eerie-aura' as AbilityId,
    name: 'Eerie Aura',
    description: 'On entry, the foe becomes more susceptible to status for a few turns.',
    devDescription: 'On entry, the foe\u2019s status susceptibility rises 25% for 3 turns.',
  },
  'swagger-king': {
    id: 'swagger-king' as AbilityId,
    name: 'Swagger King',
    description: 'On entry, it raises its Attack and confuses the foe.',
    devDescription: 'On entry, +1 Attack and the foe is confused for 2 turns.',
  },
  download: {
    id: 'download' as AbilityId,
    name: 'Download',
    description: 'On entry, it raises whichever offensive stat suits the foe better.',
    devDescription: 'On entry, +1 to its higher Attack or Special Attack vs the foe.',
  },
  menace: {
    id: 'menace' as AbilityId,
    name: 'Menace',
    description: 'On entry against a statused foe, it raises its Attack a stage.',
  },
  'gale-force': {
    id: 'gale-force' as AbilityId,
    name: 'Gale Force',
    description: 'Below a third of its HP, its Flying moves hit harder.',
    devDescription: 'Below a third of its HP, its Flying moves hit at 1.5\u00d7 power.',
  },
  'sand-rush': {
    id: 'sand-rush' as AbilityId,
    name: 'Sand Rush',
    description: 'Below a third of its HP, its Ground moves hit harder.',
    devDescription: 'Below a third of its HP, its Ground moves hit at 1.5\u00d7 power.',
  },
  'snow-cloak': {
    id: 'snow-cloak' as AbilityId,
    name: 'Snow Cloak',
    description: 'Below a third of its HP, its Ice moves hit harder.',
    devDescription: 'Below a third of its HP, its Ice moves hit at 1.5\u00d7 power.',
  },
  'volt-fury': {
    id: 'volt-fury' as AbilityId,
    name: 'Volt Fury',
    description: 'Below a third of its HP, its Electric moves hit harder.',
    devDescription: 'Below a third of its HP, its Electric moves hit at 1.5\u00d7 power.',
  },
  'shadow-rush': {
    id: 'shadow-rush' as AbilityId,
    name: 'Shadow Rush',
    description: 'Below a third of its HP, its Dark moves hit harder.',
    devDescription: 'Below a third of its HP, its Dark moves hit at 1.5\u00d7 power.',
  },
  'steel-heart': {
    id: 'steel-heart' as AbilityId,
    name: 'Steel Heart',
    description: 'Below a third of its HP, its Steel moves hit harder.',
    devDescription: 'Below a third of its HP, its Steel moves hit at 1.5\u00d7 power.',
  },
  'fairy-wrath': {
    id: 'fairy-wrath' as AbilityId,
    name: 'Fairy Wrath',
    description: 'Below a third of its HP, its Fairy moves hit harder.',
    devDescription: 'Below a third of its HP, its Fairy moves hit at 1.5\u00d7 power.',
  },
  'rebel-spirit': {
    id: 'rebel-spirit' as AbilityId,
    name: 'Rebel Spirit',
    description: 'Below a third of its HP, its Fighting moves hit harder.',
    devDescription: 'Below a third of its HP, its Fighting moves hit at 1.5\u00d7 power.',
  },
  'heavy-hitter': {
    id: 'heavy-hitter' as AbilityId,
    name: 'Heavy Hitter',
    description: 'Its strongest attacks hit even harder.',
    devDescription: 'Moves of 90 power or higher deal 1.15\u00d7 damage.',
  },
  finisher: {
    id: 'finisher' as AbilityId,
    name: 'Finisher',
    description: 'Strikes harder against badly wounded foes.',
    devDescription: 'Deals 1.25\u00d7 damage to foes below 30% HP.',
  },
  opportunist: {
    id: 'opportunist' as AbilityId,
    name: 'Opportunist',
    description: 'Strikes harder against foes afflicted by status.',
    devDescription: 'Deals 1.15\u00d7 damage to statused foes.',
  },
  showboat: {
    id: 'showboat' as AbilityId,
    name: 'Showboat',
    description: 'Hits harder while its stats are raised.',
    devDescription: 'Deals 1.12\u00d7 damage while any of its stats are boosted.',
  },
  underdog: {
    id: 'underdog' as AbilityId,
    name: 'Underdog',
    description: 'Hits harder while its stats are lowered.',
    devDescription: 'Deals 1.15\u00d7 damage while any of its stats are lowered.',
  },
  rival: {
    id: 'rival' as AbilityId,
    name: 'Rival',
    description: 'Strikes harder against foes that share one of its types.',
    devDescription: 'Deals 1.12\u00d7 damage to foes sharing a type.',
  },
  predator: {
    id: 'predator' as AbilityId,
    name: 'Predator',
    description: 'Strikes harder against foes of a different type.',
    devDescription: 'Deals 1.1\u00d7 damage to foes with no shared type.',
  },
  'opening-act': {
    id: 'opening-act' as AbilityId,
    name: 'Opening Act',
    description: 'Its first attack each battle hits harder.',
    devDescription: 'Its first attack each battle deals 1.25\u00d7 damage.',
  },
  'slow-start': {
    id: 'slow-start' as AbilityId,
    name: 'Slow Start',
    description: 'It starts sluggish, then fights above its weight once warmed up.',
    devDescription: 'Deals 0.8\u00d7 damage for the first few turns, then 1.12\u00d7 afterward.',
  },
  reckless: {
    id: 'reckless' as AbilityId,
    name: 'Reckless',
    description: 'Recoil moves hit harder, but the recoil hurts more too.',
    devDescription: 'Recoil moves deal and take 1.25\u00d7 damage.',
  },
  prankster: {
    id: 'prankster' as AbilityId,
    name: 'Prankster',
    description: 'Its status moves go first.',
    devDescription: 'Status moves gain +1 priority.',
  },
  'sheer-cold': {
    id: 'sheer-cold' as AbilityId,
    name: 'Sheer Cold',
    description: 'Its Ice moves pierce resistances and hit harder.',
    devDescription: 'Ice moves deal 1.1\u00d7 damage and ignore type resistances.',
  },
  filter: {
    id: 'filter' as AbilityId,
    name: 'Filter',
    description: 'Takes less damage from super-effective hits.',
    devDescription: 'Takes only 0.85\u00d7 from super-effective hits.',
  },
  'fur-coat': {
    id: 'fur-coat' as AbilityId,
    name: 'Fur Coat',
    description: 'Physical hits barely graze it, but special attacks hurt more.',
    devDescription: 'Takes 0.75\u00d7 from physical hits and 1.2\u00d7 from special hits.',
  },
  'filter-down': {
    id: 'filter-down' as AbilityId,
    name: 'Filter Down',
    description: 'The foe\u2019s stat boosts count for less against it.',
    devDescription: 'Each of the foe\u2019s positive stat stages counts as one lower.',
  },
  'natural-cure': {
    id: 'natural-cure' as AbilityId,
    name: 'Natural Cure',
    description: 'Leaving battle clears its status.',
  },
  hydration: {
    id: 'hydration' as AbilityId,
    name: 'Hydration',
    description: 'Every few turns, it shakes off its status.',
    devDescription: 'Cures its status every 3 turns.',
  },
  'second-wind': {
    id: 'second-wind' as AbilityId,
    name: 'Second Wind',
    description: 'Once per battle, dropping low on HP triggers a burst of healing.',
    devDescription: 'Once per battle, at 1/3 HP or below, heals 25% of its max HP.',
  },
  'plot-armor': {
    id: 'plot-armor' as AbilityId,
    name: 'Plot Armor',
    description: 'Once per battle, it survives a knockout hit while above half health.',
    devDescription: 'Once per battle, endures a knockout hit while above 50% HP.',
  },
  'shield-dust': {
    id: 'shield-dust' as AbilityId,
    name: 'Shield Dust',
    description: 'About half the time, added move effects fail against it.',
    devDescription: '50% chance added move effects fail against it.',
  },
  'white-smoke': {
    id: 'white-smoke' as AbilityId,
    name: 'White Smoke',
    description: 'The foe can never raise its stats.',
  },
  'long-reach': {
    id: 'long-reach' as AbilityId,
    name: 'Long Reach',
    description: 'Its attacks never make contact.',
  },
  'effect-spore': {
    id: 'effect-spore' as AbilityId,
    name: 'Effect Spore',
    description: 'A foe that lands a contact hit may be afflicted by a random status.',
    devDescription: '30% chance a contact hit inflicts a random status.',
  },
  sticky: {
    id: 'sticky' as AbilityId,
    name: 'Sticky',
    description: 'A foe that lands a contact hit has its Speed lowered.',
    devDescription: 'Contact lowers the attacker\u2019s Speed by 1 stage.',
  },
  'cursed-body': {
    id: 'cursed-body' as AbilityId,
    name: 'Cursed Body',
    description: 'A foe that lands a contact hit may have that move sealed briefly.',
    devDescription: '25% chance a contact hit seals that move for 1 turn.',
  },
  'perish-body': {
    id: 'perish-body' as AbilityId,
    name: 'Perish Body',
    description: 'Contact triggers a countdown that chips both combatants for a few turns.',
    devDescription: 'Contact starts a 3-turn countdown; both take 1/3 max HP chip each turn.',
  },
  'iron-barbs': {
    id: 'iron-barbs' as AbilityId,
    name: 'Iron Barbs',
    description: 'A foe that lands a contact hit takes recoil damage.',
    devDescription: 'Contact deals 1/8 max HP recoil to the attacker.',
  },
  'toxic-boost': {
    id: 'toxic-boost' as AbilityId,
    name: 'Toxic Boost',
    description: 'While poisoned, its physical attacks hit harder.',
    devDescription: 'While poisoned, physical attacks deal 1.3\u00d7 damage.',
  },
  'flare-boost': {
    id: 'flare-boost' as AbilityId,
    name: 'Flare Boost',
    description: 'While burned, its special attacks hit harder.',
    devDescription: 'While burned, special attacks deal 1.3\u00d7 damage.',
  },
  unburden: {
    id: 'unburden' as AbilityId,
    name: 'Unburden',
    description: 'Gaining a status once per battle sharply raises its Speed.',
    devDescription: 'Once per battle, gaining a status grants +2 Speed.',
  },
  pacifist: {
    id: 'pacifist' as AbilityId,
    name: 'Pacifist',
    description: 'Status moves land more often, but its attacks hit a little softer.',
    devDescription: 'Status accuracy \u00d71.2; damage dealt \u00d70.95.',
  },
  stall: {
    id: 'stall' as AbilityId,
    name: 'Stall',
    description: 'While it avoids attacking, it slowly recovers HP each turn.',
    devDescription: 'While it uses only setup moves, heals 1/16 max HP per turn.',
  },
  pressure: {
    id: 'pressure' as AbilityId,
    name: 'Pressure',
    description: 'Foes burn through PP faster when targeting it.',
    devDescription: 'Foes lose double PP when using moves against it.',
  },
  'super-luck': {
    id: 'super-luck' as AbilityId,
    name: 'Super Luck',
    description: 'Critical hits land more often and strike harder.',
    devDescription: 'Critical hit rate \u00d71.5; critical hit damage \u00d71.2.',
  },
  'compound-eyes': {
    id: 'compound-eyes' as AbilityId,
    name: 'Compound Eyes',
    description: 'Its accuracy is sharply raised.',
    devDescription: 'Accuracy \u00d71.15.',
  },
  'no-guard': {
    id: 'no-guard' as AbilityId,
    name: 'No Guard',
    description: 'Its attacks and the foe\u2019s attacks always connect.',
  },
  oblivious: {
    id: 'oblivious' as AbilityId,
    name: 'Oblivious',
    description: 'Taunt and intimidation have no effect on it.',
  },
  'wonder-guard': {
    id: 'wonder-guard' as AbilityId,
    name: 'Wonder Guard',
    description: 'Only super-effective hits can damage it.',
  },
  gravity: {
    id: 'gravity' as AbilityId,
    name: 'Gravity',
    description: 'Both combatants take slightly more damage from every hit.',
    devDescription: 'Both combatants take 1.08\u00d7 damage from all hits.',
  },
  trickster: {
    id: 'trickster' as AbilityId,
    name: 'Trickster',
    description: 'Confusion comes easily, but self-inflicted confusion hurts less.',
    devDescription: 'Confusion is easier to inflict; confused self-damage is halved.',
  },
  moody: {
    id: 'moody' as AbilityId,
    name: 'Moody',
    description: 'Each turn, one stat soars and another plummets at random.',
    devDescription: 'Each turn, +2 to one random stat and \u22121 to another random stat.',
  },
  'color-change': {
    id: 'color-change' as AbilityId,
    name: 'Color Change',
    description: 'After being hit, it resists that move\u2019s type until struck again.',
    devDescription: 'After being hit, takes 0.85\u00d7 from that move type until the next hit.',
  },
};
