// AUTO-GENERATED by scripts/build-backgrounds.mjs — do not edit by hand.
// Battle backdrop keys, each a file at public/sprites/backgrounds/<key>.png,
// sliced from the pixel-art battle-background sheets. Selection logic (which
// scene a battle uses) lives in src/game/backgrounds.ts.
export const BACKGROUNDS = [
  'woodland-day',
  'woodland-afternoon',
  'woodland-night',
  'plains-day',
  'plains-afternoon',
  'plains-night',
  'mountain-day',
  'mountain-afternoon',
  'mountain-night',
  'autumn-day',
  'autumn-afternoon',
  'autumn-night',
  'cave-blue',
  'cave-sand',
  'cave-snow',
  'cave-lava',
  'cliff-day',
  'cliff-afternoon',
  'cliff-night',
  'pier-day',
  'pier-afternoon',
  'pier-night',
  'meadow-day',
  'meadow-afternoon',
  'meadow-night',
  'court-day',
  'court-afternoon',
  'court-night',
  'town-day',
  'town-afternoon',
  'town-night',
] as const;

export type Background = (typeof BACKGROUNDS)[number];
