// AUTO-GENERATED by scripts/build-backgrounds.mjs — do not edit by hand.
// Battle backdrop keys, each a file at public/sprites/backgrounds/<key>.png,
// sliced from the hand-drawn battle-scenes sheet. Selection logic (which biome
// an opponent fights in) lives in src/game/backgrounds.ts.
export const BACKGROUNDS = [
  'forest',
  'route',
  'meadow',
  'gym',
  'canyon',
  'cave',
  'beach',
  'cavern',
  'seafloor',
  'abyss',
  'shore',
  'volcano',
  'desert',
  'glacier',
  'savanna',
] as const;

export type Background = (typeof BACKGROUNDS)[number];
