// AUTO-GENERATED by scripts/build-backgrounds.mjs — do not edit by hand.
// Battle backdrop keys, each a file at public/sprites/backgrounds/<key>.png,
// sliced from the Pokémon Platinum battle-background rip. Selection logic lives
// in src/game/backgrounds.ts.
//
// BIOME backdrops come in day/afternoon/night and are themed to an opponent's
// type. SPECIAL arenas are the one-off Elite Four / Champion / Frontier stages.
export const BIOME_BACKGROUNDS = [
  'field-day',
  'field-afternoon',
  'field-night',
  'surf-day',
  'surf-afternoon',
  'surf-night',
  'dirt-day',
  'dirt-afternoon',
  'dirt-night',
  'forest-day',
  'forest-afternoon',
  'forest-night',
  'rocky-day',
  'rocky-afternoon',
  'rocky-night',
  'snow-day',
  'snow-afternoon',
  'snow-night',
  'indoor-1',
  'indoor-2',
  'indoor-3',
  'cave-1',
  'cave-2',
  'cave-3',
] as const;

export const SPECIAL_BACKGROUNDS = [
  'aaron',
  'bertha',
  'flint',
  'lucian',
  'cynthia',
  'distortion',
  'battle-tower',
  'battle-factory',
  'battle-arcade',
  'battle-castle',
  'battle-hall',
] as const;

export type BiomeBackground = (typeof BIOME_BACKGROUNDS)[number];
export type SpecialBackground = (typeof SPECIAL_BACKGROUNDS)[number];
