// AUTO-GENERATED by scripts/build-trainers.mjs — do not edit by hand.
// Overworld trainer sprites + metadata, grouped by opponent category. Files live
// at public/sprites/trainers/<key>.png (front-facing icon) and .gif (idle loop).
// `gender` is the sprite's sex ('x' = unisex/ambiguous); roadside sprites carry
// their trainer `cls`, and the famous tiers carry the canonical character `name`.
export type TrainerCategory = 'random' | 'gym' | 'elite' | 'champion';
export type TrainerGender = 'm' | 'f' | 'x';

export interface TrainerSprite {
  key: string;
  gender: TrainerGender;
  /** Canonical character depicted (gym / elite / champion). */
  name?: string;
  /** Trainer-class title (roadside "random" trainers). */
  cls?: string;
}

export const TRAINER_SPRITES: Record<TrainerCategory, readonly TrainerSprite[]> = {
  random: [
    {"key":"random-ace-trainer-f","gender":"f","cls":"Ace Trainer"},
    {"key":"random-ace-trainer-m","gender":"m","cls":"Ace Trainer"},
    {"key":"random-artist","gender":"m","cls":"Artist"},
    {"key":"random-backpacker-f","gender":"f","cls":"Backpacker"},
    {"key":"random-backpacker-m","gender":"m","cls":"Backpacker"},
    {"key":"random-baker","gender":"f","cls":"Baker"},
    {"key":"random-battle-girl","gender":"f","cls":"Battle Girl"},
    {"key":"random-beauty","gender":"f","cls":"Beauty"},
    {"key":"random-black-belt","gender":"m","cls":"Black Belt"},
    {"key":"random-breeder-f","gender":"f","cls":"Pokémon Breeder"},
    {"key":"random-breeder-m","gender":"m","cls":"Pokémon Breeder"},
    {"key":"random-cyclist-f","gender":"f","cls":"Cyclist"},
    {"key":"random-cyclist-m","gender":"m","cls":"Cyclist"},
    {"key":"random-dancer","gender":"m","cls":"Dancer"},
    {"key":"random-depot-agent","gender":"m","cls":"Depot Agent"},
    {"key":"random-doctor","gender":"m","cls":"Doctor"},
    {"key":"random-fisher","gender":"m","cls":"Fisherman"},
    {"key":"random-gentleman","gender":"m","cls":"Gentleman"},
    {"key":"random-guitarist","gender":"m","cls":"Guitarist"},
    {"key":"random-harlequin","gender":"m","cls":"Harlequin"},
    {"key":"random-hiker","gender":"m","cls":"Hiker"},
    {"key":"random-janitor","gender":"m","cls":"Janitor"},
    {"key":"random-lady","gender":"f","cls":"Lady"},
    {"key":"random-lass","gender":"f","cls":"Lass"},
    {"key":"random-maid","gender":"f","cls":"Maid"},
    {"key":"random-musician","gender":"m","cls":"Musician"},
    {"key":"random-nurse","gender":"f","cls":"Nurse"},
    {"key":"random-nursery-aide","gender":"f","cls":"Nursery Aide"},
    {"key":"random-parasol-lady","gender":"f","cls":"Parasol Lady"},
    {"key":"random-pilot","gender":"m","cls":"Pilot"},
    {"key":"random-poke-fan-f","gender":"f","cls":"PokéFan"},
    {"key":"random-poke-fan-m","gender":"m","cls":"PokéFan"},
    {"key":"random-policeman","gender":"m","cls":"Police Officer"},
    {"key":"random-preschooler-f","gender":"f","cls":"Preschooler"},
    {"key":"random-preschooler-m","gender":"m","cls":"Preschooler"},
    {"key":"random-psychic-f","gender":"f","cls":"Psychic"},
    {"key":"random-psychic-m","gender":"m","cls":"Psychic"},
    {"key":"random-ranger-f","gender":"f","cls":"Pokémon Ranger"},
    {"key":"random-ranger-m","gender":"m","cls":"Pokémon Ranger"},
    {"key":"random-rich-boy","gender":"m","cls":"Rich Boy"},
    {"key":"random-roughneck","gender":"m","cls":"Roughneck"},
    {"key":"random-school-kid-f","gender":"f","cls":"Schoolkid"},
    {"key":"random-school-kid-m","gender":"m","cls":"Schoolkid"},
    {"key":"random-scientist-f","gender":"f","cls":"Scientist"},
    {"key":"random-scientist-m","gender":"m","cls":"Scientist"},
    {"key":"random-socialite","gender":"f","cls":"Socialite"},
    {"key":"random-swimmer-f","gender":"f","cls":"Swimmer"},
    {"key":"random-swimmer-m","gender":"m","cls":"Swimmer"},
    {"key":"random-veteran-f","gender":"f","cls":"Veteran"},
    {"key":"random-veteran-m","gender":"m","cls":"Veteran"},
    {"key":"random-waiter","gender":"m","cls":"Waiter"},
    {"key":"random-waitress","gender":"f","cls":"Waitress"},
    {"key":"random-worker","gender":"m","cls":"Worker"},
    {"key":"random-youngster","gender":"m","cls":"Youngster"},
  ],
  gym: [
    {"key":"gym-01","gender":"m","name":"Chili"},
    {"key":"gym-02","gender":"f","name":"Lenora"},
    {"key":"gym-03","gender":"m","name":"Burgh"},
    {"key":"gym-04","gender":"f","name":"Elesa"},
    {"key":"gym-05","gender":"m","name":"Clay"},
    {"key":"gym-06","gender":"f","name":"Skyla"},
    {"key":"gym-07","gender":"m","name":"Brycen"},
    {"key":"gym-08","gender":"m","name":"Drayden"},
    {"key":"gym-09","gender":"m","name":"Cheren"},
    {"key":"gym-10","gender":"f","name":"Roxie"},
    {"key":"gym-11","gender":"m","name":"Marlon"},
  ],
  elite: [
    {"key":"elite-01","gender":"f","name":"Shauntal"},
    {"key":"elite-02","gender":"m","name":"Grimsley"},
    {"key":"elite-03","gender":"f","name":"Caitlin"},
    {"key":"elite-04","gender":"m","name":"Marshal"},
  ],
  champion: [
    {"key":"champion-01","gender":"m","name":"Alder"},
    {"key":"champion-02","gender":"f","name":"Iris"},
    {"key":"champion-03","gender":"m","name":"Benga"},
  ],
};
