// AUTO-GENERATED by scripts/build-trainers.mjs — do not edit by hand.
// Overworld trainer sprites, grouped by opponent category. Files live at
// public/sprites/trainers/<key>.png (front-facing icon) and .gif (idle loop).
export type TrainerCategory = 'random' | 'gym' | 'elite' | 'champion';

export const TRAINER_SPRITES: Record<TrainerCategory, readonly string[]> = {
  random: ["random-00","random-01","random-02","random-03","random-04","random-05","random-06","random-07","random-08","random-09","random-10","random-11","random-12","random-13","random-14","random-15","random-16","random-17","random-18","random-19","random-20","random-21","random-22","random-23","random-24","random-25","random-26","random-27","random-28","random-29","random-30","random-31","random-32","random-33","random-34","random-35","random-36","random-37","random-38","random-39"],
  gym: ["gym-01","gym-02","gym-03","gym-04","gym-05","gym-06","gym-07","gym-08","gym-09","gym-10","gym-11"],
  elite: ["elite-01","elite-02","elite-03","elite-04"],
  champion: ["champion-01","champion-02"],
};
