"""
Body metrics of every bundled PMD battle sprite, for drawing them at 2x.

PMD frames of every anim share one origin at the canvas centre, but each
species' canvas carries different padding, so the canvas size says little about
the visible body. For each species this reads AnimData.xml and the sheet its
resting loop renders (Walk, else Idle, as resolvePmdAnim picks for 'idle',
including its RESTING_OVERRIDE) and measures, over every frame of the
direction rows the battle shows (src/game/pmd.ts DIR_ROW: player row 3, foe
row 7; row 0 when the sheet has fewer rows, as dirRow does):

  h     the tallest opaque bounding box, in source px;
  foot  the lowest feet line below the canvas centre (bbox bottom - fh/2).

It writes src/game/pmdBodies.gen.ts. Outputs are generated: rerun this script
instead of editing them.

    python3 scripts/build-pmd-bodies.py [--sprites=public/sprites/pmd]
"""
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "game" / "pmdBodies.gen.ts"
# Battle facing rows (keep in step with DIR_ROW in src/game/pmd.ts).
ROWS = [3, 7]
# The resting loop's sheet chain (keep in step with FALLBACKS.idle and
# RESTING_OVERRIDE in src/game/pmd.ts).
RESTING = ["Walk", "Idle"]
RESTING_OVERRIDE = {51: ["Idle", "Walk"]}


def parse_anims(xml: str) -> dict:
    """Name -> {copyOf} or {fw, fh}, from AnimData.xml."""
    anims = {}
    for block in re.findall(r"<Anim>([\s\S]*?)</Anim>", xml):
        name = re.search(r"<Name>([^<]+)</Name>", block)
        if not name:
            continue
        copy_of = re.search(r"<CopyOf>([^<]+)</CopyOf>", block)
        if copy_of:
            anims[name.group(1)] = {"copyOf": copy_of.group(1)}
            continue
        fw = re.search(r"<FrameWidth>(\d+)</FrameWidth>", block)
        fh = re.search(r"<FrameHeight>(\d+)</FrameHeight>", block)
        if fw and fh:
            anims[name.group(1)] = {"fw": int(fw.group(1)), "fh": int(fh.group(1))}
    return anims


def resolve(anims: dict, name: str):
    """Follow CopyOf to the concrete sheet name and its frame size."""
    seen = set()
    while name in anims and "copyOf" in anims[name]:
        if name in seen:
            return None
        seen.add(name)
        name = anims[name]["copyOf"]
    anim = anims.get(name)
    return (name, anim["fw"], anim["fh"]) if anim else None


def measure(sprites: Path, dex_id: int):
    """(h, foot) for one species, or None when it has no resting sheet."""
    anims = parse_anims((sprites / str(dex_id) / "AnimData.xml").read_text())
    for want in RESTING_OVERRIDE.get(dex_id, RESTING):
        found = resolve(anims, want)
        if not found:
            continue
        sheet, fw, fh = found
        path = sprites / str(dex_id) / f"{sheet}-Anim.png"
        if not path.exists():
            continue
        img = Image.open(path).convert("RGBA")
        alpha = img.getchannel("A")
        cols, rows = img.width // fw, img.height // fh
        battle_rows = sorted({row if row < rows else 0 for row in ROWS})
        h, foot = 0, None
        for row in battle_rows:
            for col in range(cols):
                box = alpha.crop((col * fw, row * fh, (col + 1) * fw, (row + 1) * fh)).getbbox()
                if not box:
                    continue
                _, top, _, bottom = box
                h = max(h, bottom - top)
                below = bottom - fh / 2
                foot = below if foot is None else max(foot, below)
        if h > 0:
            # fh is even for every PMD sheet, so this is a whole number.
            return h, int(foot) if float(foot).is_integer() else foot
    return None


def main() -> None:
    sprites = ROOT / "public" / "sprites" / "pmd"
    for arg in sys.argv[1:]:
        if arg.startswith("--sprites="):
            sprites = Path(arg.split("=", 1)[1]).resolve()
    ids = sorted(int(p.name) for p in sprites.iterdir() if p.name.isdigit() and (p / "AnimData.xml").exists())
    lines = []
    missing = []
    for dex_id in ids:
        body = measure(sprites, dex_id)
        if body is None:
            missing.append(dex_id)
            continue
        h, foot = body
        lines.append(f"  {dex_id}: {{ h: {h}, foot: {foot} }},")
    header = """// AUTO-GENERATED by scripts/build-pmd-bodies.py — do not edit by hand.
// Maps National Dex id -> the visible body of the PMD sheet that species' resting
// loop renders (Walk, else Idle), measured over the battle's facing rows, in
// source pixels.
// `h` is the tallest opaque bounding box; `foot` is how far the feet sit below
// the frame's centre (every anim of a species shares that centre). See
// pmdFrameBox in src/game/pmd.ts.
export interface PmdBody {
  /** Visible body height in source pixels. */
  h: number;
  /** Feet line below the frame centre in source pixels. */
  foot: number;
}

export const PMD_BODIES: Record<number, PmdBody> = {
"""
    OUT.write_text(header + "\n".join(lines) + "\n};\n")
    print(f"wrote {OUT} ({len(lines)} species)")
    if missing:
        print(f"no resting sheet: {missing}", file=sys.stderr)


if __name__ == "__main__":
    main()
