// Fetches ALL base-species Pokémon (national dex 1..MAX) from the PokeAPI
// GraphQL endpoint and writes src/game/pokedex.gen.ts, classifying each as
// normal / legendary / mythical.
//
// Run:  npx tsx scripts/gen-pokedex.ts
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MAX_DEX = 1025;
const ENDPOINT = 'https://beta.pokeapi.co/graphql/v1beta';

interface GqlPokemon {
  id: number;
  name: string;
  pokemon_v2_pokemontypes: { pokemon_v2_type: { name: string } }[];
  pokemon_v2_pokemonstats: {
    base_stat: number;
    pokemon_v2_stat: { name: string };
  }[];
  pokemon_v2_pokemonspecy: {
    is_legendary: boolean;
    is_mythical: boolean;
  } | null;
}

type Tier = 'normal' | 'legendary' | 'mythical';

function title(name: string): string {
  return name
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

async function main() {
  const query = `query {
    pokemon_v2_pokemon(where: {id: {_lte: ${MAX_DEX}}}, order_by: {id: asc}, limit: 5000) {
      id
      name
      pokemon_v2_pokemontypes { pokemon_v2_type { name } }
      pokemon_v2_pokemonstats { base_stat pokemon_v2_stat { name } }
      pokemon_v2_pokemonspecy { is_legendary is_mythical }
    }
  }`;

  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) throw new Error(`GraphQL ${res.status}`);
  const json = (await res.json()) as {
    data: { pokemon_v2_pokemon: GqlPokemon[] };
  };
  const rows = json.data.pokemon_v2_pokemon;
  console.error(`Fetched ${rows.length} Pokémon`);

  const out: string[] = [];
  let legendary = 0;
  let mythical = 0;

  for (const p of rows) {
    const stat = (n: string) =>
      p.pokemon_v2_pokemonstats.find((s) => s.pokemon_v2_stat.name === n)
        ?.base_stat ?? 0;
    const hp = stat('hp');
    // Physical / Energy split: PokeAPI's attack/defense become the physical
    // pair, special-attack/special-defense become the energy pair.
    const atk = stat('attack');
    const def = stat('defense');
    const eatk = stat('special-attack');
    const edef = stat('special-defense');
    const speed = stat('speed');

    const isLeg = p.pokemon_v2_pokemonspecy?.is_legendary ?? false;
    const isMyth = p.pokemon_v2_pokemonspecy?.is_mythical ?? false;
    let tier: Tier = 'normal';
    if (isMyth) {
      tier = 'mythical';
      mythical++;
    } else if (isLeg) {
      tier = 'legendary';
      legendary++;
    }

    const types = p.pokemon_v2_pokemontypes.map((t) => t.pokemon_v2_type.name);
    out.push(
      `  { id: ${p.id}, name: ${JSON.stringify(
        title(p.name),
      )}, types: ${JSON.stringify(types)}, stats: { hp: ${hp}, atk: ${atk}, eatk: ${eatk}, def: ${def}, edef: ${edef}, spd: ${speed} }, tier: ${JSON.stringify(
        tier,
      )} },`,
    );
  }

  const header = `// AUTO-GENERATED by scripts/gen-pokedex.ts — do not edit by hand.
// ${rows.length} Pokémon · ${legendary} legendary · ${mythical} mythical
import type { DexEntry } from './types';

export const RAW_DEX: DexEntry[] = [
${out.join('\n')}
];
`;
  const target = resolve(import.meta.dirname, '../src/game/pokedex.gen.ts');
  writeFileSync(target, header);
  console.error(
    `\nWrote ${out.length} entries (${legendary} legendary, ${mythical} mythical) to ${target}`,
  );
}

main();
