// Fetches a curated roster from PokeAPI and writes src/game/pokedex.gen.ts.
// Run:  npx tsx scripts/gen-pokedex.ts
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Curated roster with broad type coverage (gen 1–4 fan favourites).
const IDS = [
  // Fire
  6, 59, 136, 38, 78, 126, 157, 229,
  // Water
  9, 130, 134, 131, 121, 350, 160, 80,
  // Grass
  3, 45, 103, 254, 154, 114, 470, 407,
  // Electric
  25, 26, 135, 125, 82, 181, 310, 145,
  // Psychic
  65, 196, 122, 97, 282, 376, 199,
  // Dragon
  149, 373, 330, 230, 334, 445, 612,
  // Coverage / other types
  143, 94, 68, 248, 448, 212, 306, 232, 34, 473, 461, 468, 142, 169,
];

interface RawStat {
  base_stat: number;
  stat: { name: string };
}

function role(
  hp: number,
  atk: number,
  def: number,
  spd: number,
): 'Sweeper' | 'Tank' | 'Support' | 'Bruiser' {
  if (spd >= 95 && atk >= 95) return 'Sweeper';
  if (hp >= 95 && spd < 75) return 'Tank';
  if (atk >= 110) return 'Bruiser';
  if (def >= 100) return 'Tank';
  return 'Support';
}

function title(name: string): string {
  return name
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

async function main() {
  const ids = [...new Set(IDS)];
  const out: string[] = [];
  for (const id of ids) {
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
    if (!res.ok) {
      console.error(`Failed ${id}: ${res.status}`);
      continue;
    }
    const data = (await res.json()) as {
      name: string;
      types: { type: { name: string } }[];
      stats: RawStat[];
    };
    const get = (n: string) =>
      data.stats.find((s) => s.stat.name === n)?.base_stat ?? 0;
    const hp = get('hp');
    const attack = get('attack');
    const defense = get('defense');
    const spa = get('special-attack');
    const spd2 = get('special-defense');
    const speed = get('speed');
    // Collapse phys/special into single atk/def so the engine stays simple
    // while still honouring special attackers.
    const atk = Math.round((attack + spa) / 2);
    const def = Math.round((defense + spd2) / 2);
    const types = data.types.map((t) => t.type.name);
    const name = title(data.name);
    out.push(
      `  { id: ${id}, name: ${JSON.stringify(name)}, types: ${JSON.stringify(
        types,
      )}, stats: { hp: ${hp}, atk: ${atk}, def: ${def}, spd: ${speed} }, role: ${JSON.stringify(
        role(hp, atk, def, speed),
      )} },`,
    );
    console.error(`ok ${id} ${name} [${types.join('/')}]`);
  }

  const header = `// AUTO-GENERATED by scripts/gen-pokedex.ts — do not edit by hand.
import type { DexEntry } from './types';

export const RAW_DEX: DexEntry[] = [
${out.join('\n')}
];
`;
  const target = resolve(import.meta.dirname, '../src/game/pokedex.gen.ts');
  writeFileSync(target, header);
  console.error(`\nWrote ${out.length} entries to ${target}`);
}

main();
