// Fetches every base-species evolution link (national dex 1..MAX) from the
// PokeAPI GraphQL endpoint and writes src/game/evolutions.gen.ts: a map from a
// species' dex id to the dex id(s) it can evolve INTO. Branched evolutions
// (e.g. Eevee) list every option; species with no next stage are omitted.
//
// Run:  npx tsx scripts/gen-evolutions.ts
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MAX_DEX = 1025;
const ENDPOINT = 'https://beta.pokeapi.co/graphql/v1beta';

interface GqlSpecies {
  id: number;
  name: string;
  evolves_from_species_id: number | null;
}

async function main() {
  const query = `query {
    pokemon_v2_pokemonspecies(where: {id: {_lte: ${MAX_DEX}}}, order_by: {id: asc}, limit: 5000) {
      id
      name
      evolves_from_species_id
    }
  }`;

  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) throw new Error(`GraphQL ${res.status}`);
  const json = (await res.json()) as {
    data: { pokemon_v2_pokemonspecies: GqlSpecies[] };
  };
  const rows = json.data.pokemon_v2_pokemonspecies;
  console.error(`Fetched ${rows.length} species`);

  // Reverse the evolves_from link into a forward "evolves into" map.
  const evolvesInto = new Map<number, number[]>();
  for (const sp of rows) {
    const from = sp.evolves_from_species_id;
    if (from == null || from > MAX_DEX || sp.id > MAX_DEX) continue;
    const list = evolvesInto.get(from) ?? [];
    list.push(sp.id);
    evolvesInto.set(from, list);
  }

  const ids = [...evolvesInto.keys()].sort((a, b) => a - b);
  const lines = ids.map(
    (id) => `  ${id}: [${evolvesInto.get(id)!.sort((a, b) => a - b).join(', ')}],`,
  );

  const branched = ids.filter((id) => evolvesInto.get(id)!.length > 1).length;
  const header = `// AUTO-GENERATED by scripts/gen-evolutions.ts — do not edit by hand.
// ${ids.length} species with an evolution · ${branched} with branched paths
//
// Maps a species' National Dex id to the dex id(s) it can evolve INTO. In-game
// evolution ignores the real-world conditions (level, item, friendship, …): an
// Evolution Ticket lets you evolve any team member that has a next stage.

export const EVOLUTIONS: Record<number, number[]> = {
${lines.join('\n')}
};
`;
  const target = resolve(import.meta.dirname, '../src/game/evolutions.gen.ts');
  writeFileSync(target, header);
  console.error(`\nWrote ${ids.length} evolution entries to ${target}`);
}

main();
